services:
  pgdb:
    image: postgres
    container_name: pgdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    env_file:
      - ./server/.env

  frontend:
    build: ./frontend/
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - django-api

  django-api:
    build: ./server/
    container_name: django-api
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
    command: >
      sh -c "uv run python manage.py makemigrations && uv run python manage.py migrate &&
             uv run gunicorn betesbot.wsgi:application --bind 0.0.0.0:8000 --workers 4"

volumes:
  postgres_data:
