# Generated by Django 6.0.2 on 2026-04-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_chat_id_alter_question_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='question',
            name='citation',
            field=models.JSONField(),
        ),
        migrations.RemoveField(
            model_name='chat',
            name='chat_number',
        ),
    ]
