# Generated by Django 6.0.2 on 2026-04-14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BudgetUsage",
        ),
    ]
