CREATE DATABASE db_chatbot

--CREATE USER INFORMATION TABLE
CREATE TABLE users(
    user_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    time_stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    email_address VARCHAR(50) UNIQUE,
    password_hash VARCHAR(50)
);

--CREATE SESSION TABLE
CREATE TABLE sessions(
    session_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES users(user_id),
    time_stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--CREATE Q&As TABLE
CREATE TABLE questions(
    message_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES users(user_id),
    session_id INT REFERENCES sessions(session_id),
    time_stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    question TEXT,
    answer TEXT,
    citations TEXT
);